### PR TITLE
QoL for distributed bruteforcing

### PR DESCRIPTION
**Pull request by GijsvandenHoven**
Added a few features for if you will continue sharing the bruteforcing effort.

* Ensured a tests folder is there automatically when users pull
* optional command line parameter for the amount of values to check (default 50)
* time-to-complete estimator

image

### CODE REVIEW

**Comment by GijsvandenHoven** [comment]
It seems you also added a command line arg for 'end' , hence the merge conflict

We defined  'end' differently, however. I made it 'how many to do from start', yours just the x value to end at.

If you would like to keep it as "x value to end at"  let me know, I will need to make a minor code change for the time estimation stuff.

**Comment by nim-ka** [comment]
I think it's just so fast with the latest change that this is mostly unnecessary now

**Comment by GijsvandenHoven** [comment]
Really? impressive. That's unfortunate, I just got it working again lol.

**Comment by GijsvandenHoven** [comment]
Yeah, just tested it for myself and you got some serious speed out of it. 

It still took a few minutes to do 10 values on my crap machine, so it _might_ be worth a little bit still. But I will leave it up to you whether you want to close this PR or merge it.

One small thing that was also here that I would recommend, though. I added a `.gitkeep` file to the tests folder. It should be invisible on UNIX systems, but still force git to include the directory. So users of this code won't need to manually make this folder.

**Comment by nim-ka** [comment]
was going to do that but forgot. I'll put it in on next commit

**Pull request closed without merging**
